policy: 'MlpPolicy'
learning_rate: 7.3e-4
buffer_size: 300000
batch_size: 256
ent_coef: 'auto'
gamma: 0.98
tau: 0.02
train_freq: 64
gradient_steps: 64
learning_starts: 10000
policy_kwargs:
  log_std_init: -3
  net_arch:
        - 400
        - 300