specs:
  - 'ensure abs "x" <= "x_limit"'
  - 'ensure abs "theta" <= "theta_limit"'
  - 'conquer abs "x" <= "x_tol"'
  - 'encourage abs "theta" <= "theta_balance"'

constants:
  - name: x_limit
    value: 2.4
    description: "world limit"
  - name: x_tol
    value: 0.25
    description: "tolerance for reaching the goal"
  - name: theta_limit
    value: 0.2095
    description: "pole angle limit which terminates the episode"
  - name: theta_balance
    value: 0.10
    description: "pole angle limit which determines the balance state"

variables:
  - name: x
    fn: "state[0]"
    min: -2.4
    max: 2.4
    description: "x position of the cart"
  - name: x_dot
    fn: "state[1]"
    min: -5.0
    max: 5.0
    description: "velocity of the cart"
  - name: theta
    fn: "state[2]"
    min: -0.2
    max: 0.2
    description: "angle of the pole"
  - name: theta_dot
    fn: "state[3]"
    min: -5.0
    max: 5.0
    description: "angular velocity of the pole"
