specs:
  - 'ensure abs "x" <= "x_limit"'
  - 'conquer "neg_dist" <= 0.0'
  - 'encourage abs "theta" <= "theta_comfort"'
  - 'encourage abs "theta_dot" <= "theta_dot_comfort"'

constants:
  - name: x_limit
    value: 1.0
    description: "normalized world limit"
  - name: half_landing_pad
    value: 0.15
    description: "half width of the landing pad"
  - name: landing_height
    value: 0.1
    description: "height of the landing pad"
  - name: theta_comfort
    value: 1.0472 # pi/3
    description: "angle limit which determines a comfortable inclination"
  - name: theta_dot_comfort
    value: 0.5
    description: "angular velocity limit which determines a comfortable fly"

variables:
  - name: x
    fn: "state[0]"
    min: -1.5
    max: 1.5
    description: "x position of the lander"
  - name: neg_dist_x
    fn: "- (x - half_landing_pad)"
    min: -1.5
    max: 1.5
    description: "negative distance to the landing pad"
  - name: "neg_dist_y"
    fn: "- (state[1] - landing_height)"
    min: -1.0
    max: 0.0
    description: "negative distance to the landing pad"
  - name: "neg_dist"
    fn: "min(neg_dist_x, neg_dist_y)"
    min: -1.5
    max: 0.0
    description: "negative distance to the landing pad"
  - name: "theta"
    fn: "state[4]"
    min: -3.14
    max: 3.14
    description: "angle of the lander"
  - name: "theta_dot"
    fn: "state[5]"
    min: -5.0
    max: 5.0
    description: "angular velocity of the lander"